apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - configmap.yaml

namespace: default

commonLabels:
  app: garry-bot
  managed-by: kustomize

images:
  - name: organisely/garry-bot
    newTag: latest
