apiVersion: v1
kind: Service
metadata:
  name: garry-bot
  labels:
    app: garry-bot
spec:
  type: ClusterIP
  ports:
  - name: webhook
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: garry-bot
